### ISSUE TITLE
Confidence intervals

### ISSUE THREAD

**Issue by jmvaldes** [reifjulian/wyoung#12]
Prof. Reif, 

I am very gratefull for this contribution of yours. However, I am missing the confidence intervarls for the coef calculation. Do you think is possible to add that option?

Thanks a lot, 

Dr. José M. Valdés, MD

**Comment by reifjulian** [comment]
@jmvaldes can you clarify: do you mean the usual confidence interval that would be reported by `regress`? A specific example with numbers would be helpful.

**Comment by jmvaldes** [comment]
@reifjulian exactly, for example in 
![image](https://github.com/reifjulian/wyoung/assets/65752358/f28c721f-7c7f-4239-91d4-bb83233ce0b5)
to show the confidence interval (95% CI 0.81-1.31), so is not necessary to perform every regression independently
![image](https://github.com/reifjulian/wyoung/assets/65752358/eac6530f-f7a7-47e3-9732-d0dcf4f17231)

**Comment by reifjulian** [comment]
Ok, I will consider for the next update. In the meantime, two potential workarounds:
1. Estimate confidence intervals directly using a separate regression. One can store them using `regsave, ci` and then merge them onto your `wyoung` results.
2. Calculate confidence intervals manually using normal approximation.

**Comment by jmvaldes** [comment]
Thanks a lot!
