### ISSUE TITLE
Lack of variation in one of the outcome variables

### ISSUE THREAD

**Issue by MRuzzante** [reifjulian/wyoung#3]
Hi Julian,

I have recently been using `wyoung` and it's great and handy, so thanks for sharing this public good! :blush:

Just one minor issue I came across: When including one outcome variable which has no variation across treatment (which means Stata estimates a coefficient equal to 0 and omits the standard errors), p-values are not computed, and I get the following error
> p-value not obtainable from matrix r(table)

It would be good if you could either
- better specify the error message, mentioning it arose from the regression of that outcome variable
- or still compute the adjusted p-values excluding that outcome for the rest of the variables, 
 returning a missing p-value for that outcome variable coefficient and a warning to make the user aware of this

All the best,
Matteo

**Comment by reifjulian** [comment]
@MRuzzante I think that error message may have been from an old version of `wyoung`. The current one should tell you what regression was being run when the error occurred, which would allow you to infer the outcome variable. You can install the newest version by typing the following at the Stata prompt:
```stata
net install wyoung, from("https://raw.githubusercontent.com/reifjulian/wyoung/master") replace
```
